[bastion]
bastion_node ansible_host=44.201.203.120

[application]
application_node ansible_host=10.0.2.205

[database]
database_node ansible_host=10.0.2.149

[bastion:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/Bloggin-assignment.pem

[application:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/Bloggin-assignment.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ubuntu/Bloggin-assignment.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@44.201.203.120"'

[database:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/Bloggin-assignment.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ubuntu/Bloggin-assignment.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@44.201.203.120"'
